### Upload file

POST {{host}}/file.txt
Content-Type: text/plain

< ./file.txt


### Upload file small
POST {{host}}/smallFile.txt
Content-Type: text/plain

< ./smallFile.txt


### Upload file > 1mb
POST {{host}}/bigFile.txt
Content-Type: text/plain

< ./bigFile.txt


### Get index page
GET {{host}}/


### Get file
GET {{host}}/file.txt


### Delete file
DELETE {{host}}/file.txt